/// <reference types="Cypress"/>
import HomePOM from '../pageObjects/HomePOM'
const Testdata = require('../fixtures/Testdata.json')
describe('Test Suite for Page Object Model Demo', function()
{
    const homepom = new HomePOM()
    //To Handle Uncaught Exception
    Cypress.on('uncaught:exception',(err,runnable) => {
    return false;
    })


    it('Handling multiple windows',function(){
    homepom.getApplicationURL()
    //Example for implicitly wait {timeout:15000 -> Miliseconds -> 1sec =1000 milliseconds}
    homepom.getSearchBox().type('iphone{enter}')
    //cy.get('#twotabsearchtextbox',{timeout:15000}).type('iphone{enter}')
    //we can stop the execution and click on inspector icon
    //then once we hover on an element we can see the autogenerated code like this 
    //we can click on copy to clipboard icon to copy this 
    homepom.getBestSellerMenuLink().click({force:true})
   // cy.get('[href="/gp/bestsellers/?ref_=nav_cs_bestsellers"]').click({force:true})
    //{force:true} to click some elements overlaping with the other elements 
    //cy.wait(10000)
   cy.task('getNewWindow',Testdata.SecondSiteUrl).then((url) =>{
    cy.log("THIS IS THE SECOND WINDOW URL",url)
   })
    })

})