/// <reference types="Cypress"/>
describe('Test Suite for Automation Using Element inspector', function()
{

    //To Handle Uncaught Exception
    Cypress.on('uncaught:exception',(err,runnable) => {
    return false;
    })

//Test Case
    it('My Second Test Case',function(){
    cy.visit("https://www.amazon.in/")
    //Example for implicitly wait {timeout:15000 -> Miliseconds -> 1sec =1000 milliseconds}
    cy.get('#twotabsearchtextbox',{timeout:15000}).type('iphone{enter}')
    //we can stop the execution and click on inspector icon
    //then once we hover on an element we can see the autogenerated code like this 
    //we can click on copy to clipboard icon to copy this 
    cy.get('[href="/gp/bestsellers/?ref_=nav_cs_bestsellers"]').click({force:true})
    //{force:true} to click some elements overlaping with the other elements 
    cy.wait(10000)
    expect(true).to.be(false)
    })
// To Execute multiple test suites and test cases at once we need to use below command
// npx cypress run   -> headless mode 
// npx cypress run --headed   -> headed mode will open the browser and starts the execution

})